name: DayPass Auto Package Pipeline

on:
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    
    container:
      image: alpine:latest

    steps:
      - name: Checkout Repository Source
        uses: actions/checkout@v4

      - name: Install Pipeline Dependencies (Bash, Usign, Curl, Jq)
        run: |
          apk update
          # اضافه کردن مخزن edge/testing آلپاین برای پیدا کردن usign
          apk add --no-cache bash curl jq
          apk add --no-cache usign --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
          
      - name: Make Scripts Executable
        run: |
          chmod +x core/orchestrator.sh
          chmod +x core/signer.sh
          chmod +x ui/banner.sh

      - name: Run DayPass Orchestrator
        run: |
          ./core/orchestrator.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}