name: DayPass Auto Package Pipeline

on:
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Source
        uses: actions/checkout@v4 # این نسخه اوکی هست

      - name: Install Official Build Tools & Build Usign
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl build-essential cmake
          git clone https://git.openwrt.org/project/usign.git
          cd usign
          cmake .
          make
          sudo cp usign /usr/local/bin/usign
          cd .. && rm -rf usign
          echo "Usign successfully built and deployed."

      - name: Make Scripts Executable
        run: |
          chmod +x core/*.sh ui/*.sh

      - name: Run DayPass Orchestrator
        run: |
          ./core/orchestrator.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ارتقا به نسخه v4 جهت استفاده از Node جدید و حذف وارنینگ
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'output'

      # ارتقا به نسخه v5 جهت سازگاری کامل و حذف وارنینگ
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5